---
title: "p8105_hw2_kq2127"
author: "Kristal Quispe"
date: "9/29/2019"
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

## Problem 1

Read and clean Mr. Trash Wheel sheet

```{r}
prob1_data = 
  read_excel(
    path = "./data/HealthyHarborWaterWheel.xlsx",
    sheet = "Mr. Trash Wheel",
    range ="A2:N336") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = as.integer(round(sports_balls)))
 
```

Read, clean and combine 2017-2018 Precipitation data

```{r}
precip17_dt = 
  read_excel(
    path = "./data/HealthyHarborWaterWheel.xlsx",
    sheet = "2017 Precipitation",
    range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2017)

precip18_dt = 
  read_excel(
    path = "./data/HealthyHarborWaterWheel.xlsx",
    sheet = "2018 Precipitation",
    range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2018)

precip_dt =
  bind_rows(
    precip17_dt,precip18_dt) %>%
  janitor::clean_names() %>% 
  mutate(month=month.name[month])
```

## Problem 2

```{r}
pm_dt = read_csv(file="./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year)) %>% 
  select(year, month, prez_gop, prez_dem, everything(), -day) %>% 
  pivot_longer(
    prez_gop:prez_dem,
    names_to = "president",
    names_prefix = "prez_",
    values_to = "value") %>% 
  filter(value == 1) %>% 
  select(year, month, president, everything(), -value)


snp_dt = read_csv(file="./data/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year)) %>% 
  select(year, month, everything(), -day)


une_dt = read_csv(file="./data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment") %>% 
  mutate(
    month = recode(
      month,
      "jan" = "January",
      "feb" = "February",
      "mar" = "March",
      "apr" = "April",
      "may" = "May",
      "jun" = "June",
      "jul" = "July",
      "aug" = "August",
      "sep" = "September",
      "oct" = "October",
      "nov" = "November",
      "dec" = "December"))


fj_dt = left_join(pm_dt, snp_dt, by = c("year", "month"))

pb2_dt = left_join(fj_dt, une_dt, by = c("year", "month"))

pb2_dt
```

