p8105\_hw2\_kq2127
================
Kristal Quispe
9/29/2019

## Problem 1

Read and clean Mr. Trash Wheel sheet

``` r
mtw_data = 
  read_excel(
    path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "Mr. Trash Wheel",
    range ="A2:N406") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = as.integer(round(sports_balls)))
 
mtw_data
```

    ## # A tibble: 344 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_ya~
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71               13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52               14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76               18
    ## # ... with 334 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <int>,
    ## #   homes_powered <dbl>

Read, clean and combine 2017-2018 Precipitation data

``` r
precip17_dt = 
  read_excel(
    path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2017 Precipitation",
    range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2017)

precip17_dt
```

    ## # A tibble: 12 x 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  2.34  2017
    ##  2     2  1.46  2017
    ##  3     3  3.57  2017
    ##  4     4  3.99  2017
    ##  5     5  5.64  2017
    ##  6     6  1.4   2017
    ##  7     7  7.09  2017
    ##  8     8  4.44  2017
    ##  9     9  1.95  2017
    ## 10    10  0     2017
    ## 11    11  0.11  2017
    ## 12    12  0.94  2017

``` r
precip18_dt = 
  read_excel(
    path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  drop_na(total) %>% 
  mutate(year = 2018)

precip18_dt
```

    ## # A tibble: 12 x 3
    ##    month total  year
    ##    <dbl> <dbl> <dbl>
    ##  1     1  0.94  2018
    ##  2     2  4.8   2018
    ##  3     3  2.69  2018
    ##  4     4  4.69  2018
    ##  5     5  9.27  2018
    ##  6     6  4.77  2018
    ##  7     7 10.2   2018
    ##  8     8  6.45  2018
    ##  9     9 10.5   2018
    ## 10    10  2.12  2018
    ## 11    11  7.82  2018
    ## 12    12  6.11  2018

``` r
precip_dt =
  bind_rows(
    precip17_dt,precip18_dt) %>%
  janitor::clean_names() %>% 
  mutate(month = month.name[month])

precip_dt
```

    ## # A tibble: 24 x 3
    ##    month     total  year
    ##    <chr>     <dbl> <dbl>
    ##  1 January    2.34  2017
    ##  2 February   1.46  2017
    ##  3 March      3.57  2017
    ##  4 April      3.99  2017
    ##  5 May        5.64  2017
    ##  6 June       1.4   2017
    ##  7 July       7.09  2017
    ##  8 August     4.44  2017
    ##  9 September  1.95  2017
    ## 10 October    0     2017
    ## # ... with 14 more rows

The mtw\_data data set has 344 observations. The most important
variables in this data set are dumpster, year, weight\_tons,
volume\_cubic\_yards, and sports\_balls. The median number of sports
balls in a dumpster in 2017 is 8. The precip\_dt data set has 24
observations. The most important variables in this data set are year,
month and total. The total precipitation in 2018 is 70.33 units.

## Problem 2

``` r
pm_dt = read_csv(file="./data/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year)) %>% 
  select(year, month, prez_gop, prez_dem, everything(), -day) %>% 
  pivot_longer(
    prez_gop:prez_dem,
    names_to = "president",
    names_prefix = "prez_",
    values_to = "value") %>% 
  filter(value == 1) %>% 
  select(year, month, president, everything(), -value)
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

``` r
pm_dt
```

    ## # A tibble: 817 x 9
    ##     year month    president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <dbl> <chr>    <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 January  dem            23      51     253      23      45     198
    ##  2  1947 February dem            23      51     253      23      45     198
    ##  3  1947 March    dem            23      51     253      23      45     198
    ##  4  1947 April    dem            23      51     253      23      45     198
    ##  5  1947 May      dem            23      51     253      23      45     198
    ##  6  1947 June     dem            23      51     253      23      45     198
    ##  7  1947 July     dem            23      51     253      23      45     198
    ##  8  1947 August   dem            23      51     253      23      45     198
    ##  9  1947 Septemb~ dem            23      51     253      23      45     198
    ## 10  1947 October  dem            23      51     253      23      45     198
    ## # ... with 807 more rows

``` r
snp_dt = read_csv(file="./data/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year"), sep = "/") %>% 
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year)) %>% 
  select(year, month, everything(), -day)
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

``` r
snp_dt
```

    ## # A tibble: 787 x 3
    ##     year month    close
    ##    <dbl> <chr>    <dbl>
    ##  1  2015 July     2080.
    ##  2  2015 June     2063.
    ##  3  2015 May      2107.
    ##  4  2015 April    2086.
    ##  5  2015 March    2068.
    ##  6  2015 February 2104.
    ##  7  2015 January  1995.
    ##  8  2014 December 2059.
    ##  9  2014 November 2068.
    ## 10  2014 October  2018.
    ## # ... with 777 more rows

``` r
une_dt = read_csv(file="./data/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment") %>% 
  mutate(
    month = recode(
      month,
      "jan" = "January",
      "feb" = "February",
      "mar" = "March",
      "apr" = "April",
      "may" = "May",
      "jun" = "June",
      "jul" = "July",
      "aug" = "August",
      "sep" = "September",
      "oct" = "October",
      "nov" = "November",
      "dec" = "December"))
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

``` r
une_dt
```

    ## # A tibble: 816 x 3
    ##     year month     unemployment
    ##    <dbl> <chr>            <dbl>
    ##  1  1948 January            3.4
    ##  2  1948 February           3.8
    ##  3  1948 March              4  
    ##  4  1948 April              3.9
    ##  5  1948 May                3.5
    ##  6  1948 June               3.6
    ##  7  1948 July               3.6
    ##  8  1948 August             3.9
    ##  9  1948 September          3.8
    ## 10  1948 October            3.7
    ## # ... with 806 more rows

``` r
fj_dt = left_join(pm_dt, snp_dt, by = c("year", "month"))

pb2_dt = left_join(fj_dt, une_dt, by = c("year", "month"))

pb2_dt
```

    ## # A tibble: 817 x 11
    ##     year month president gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <dbl> <chr> <chr>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 Janu~ dem            23      51     253      23      45     198
    ##  2  1947 Febr~ dem            23      51     253      23      45     198
    ##  3  1947 March dem            23      51     253      23      45     198
    ##  4  1947 April dem            23      51     253      23      45     198
    ##  5  1947 May   dem            23      51     253      23      45     198
    ##  6  1947 June  dem            23      51     253      23      45     198
    ##  7  1947 July  dem            23      51     253      23      45     198
    ##  8  1947 Augu~ dem            23      51     253      23      45     198
    ##  9  1947 Sept~ dem            23      51     253      23      45     198
    ## 10  1947 Octo~ dem            23      51     253      23      45     198
    ## # ... with 807 more rows, and 2 more variables: close <dbl>,
    ## #   unemployment <dbl>

The data in the pols-month csv file was cleaned and tidyed to become the
pm\_dt data set which has 817 observations and 9 variables. This data
set contains political information regarding how many house, senate and
governor seats were then being occupied by Democrats vs. Republicans for
a given year and month. The data ranges from year 1947 to 2015. The
pm\_data set also has a column called president that shows us the party
the president belonged to for every month of a year. The key variables
in this data set are year, month and president. The snp csv file was
cleaned and tidyed to become the snp\_dt data set which contains 787
observation and 3 variables. The data ranges from year 1950 to 2015.
This data set contains information about the close for a given year and
month. The key variables in this data set are year, month and close. The
unemployment data was cleaned and tidyed and became the une\_dt data
set, which has 816 observations and 3 variables. This data describes the
unemployent rate for every month of the year between 1948 to 2015. The
key variables in this data set are year, month and unemployment. All
three of these data sets were merged together on year and month to
create one data set called pb2\_dt. This data set has 817 observations
and 11 variables. The time range for this data set is from 1947 to 2015,
and the key variables are month, year, president, close, and
unemployment.

## Problem 3

``` r
babynames_dt = read_csv(file="./data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    childs_first_name = tolower(childs_first_name),
    ethnicity = recode(ethnicity,
      "ASIAN AND PACI" = "ASIAN AND PACIFIC ISLANDER",
      "BLACK NON HISP" = "BLACK NON HISPANIC",
      "WHITE NON HISP" = "WHITE NON HISPANIC")) %>% 
  distinct()
```

    ## Parsed with column specification:
    ## cols(
    ##   `Year of Birth` = col_double(),
    ##   Gender = col_character(),
    ##   Ethnicity = col_character(),
    ##   `Child's First Name` = col_character(),
    ##   Count = col_double(),
    ##   Rank = col_double()
    ## )

``` r
babynames_dt     
```

    ## # A tibble: 12,181 x 6
    ##    year_of_birth gender ethnicity              childs_first_na~ count  rank
    ##            <dbl> <chr>  <chr>                  <chr>            <dbl> <dbl>
    ##  1          2016 FEMALE ASIAN AND PACIFIC ISL~ olivia             172     1
    ##  2          2016 FEMALE ASIAN AND PACIFIC ISL~ chloe              112     2
    ##  3          2016 FEMALE ASIAN AND PACIFIC ISL~ sophia             104     3
    ##  4          2016 FEMALE ASIAN AND PACIFIC ISL~ emily               99     4
    ##  5          2016 FEMALE ASIAN AND PACIFIC ISL~ emma                99     4
    ##  6          2016 FEMALE ASIAN AND PACIFIC ISL~ mia                 79     5
    ##  7          2016 FEMALE ASIAN AND PACIFIC ISL~ charlotte           59     6
    ##  8          2016 FEMALE ASIAN AND PACIFIC ISL~ sarah               57     7
    ##  9          2016 FEMALE ASIAN AND PACIFIC ISL~ isabella            56     8
    ## 10          2016 FEMALE ASIAN AND PACIFIC ISL~ hannah              56     8
    ## # ... with 12,171 more rows

``` r
olivia_dt =
  filter(babynames_dt, childs_first_name == "olivia") %>% 
  select (ethnicity, year_of_birth, rank) %>% 
  pivot_wider(names_from = year_of_birth, values_from = rank)

olivia_dt
```

    ## # A tibble: 4 x 7
    ##   ethnicity                  `2016` `2015` `2014` `2013` `2012` `2011`
    ##   <chr>                       <dbl>  <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ## 1 ASIAN AND PACIFIC ISLANDER      1      1      1      3      3      4
    ## 2 BLACK NON HISPANIC              8      4      8      6      8     10
    ## 3 HISPANIC                       13     16     16     22     22     18
    ## 4 WHITE NON HISPANIC              1      1      1      1      4      2

``` r
boy_dt =
  filter(babynames_dt, gender == "MALE", rank == 1) %>% 
  select (ethnicity, year_of_birth, childs_first_name) %>% 
  pivot_wider(names_from = year_of_birth, values_from = childs_first_name)
  
boy_dt
```

    ## # A tibble: 4 x 7
    ##   ethnicity                  `2016` `2015` `2014` `2013` `2012` `2011` 
    ##   <chr>                      <chr>  <chr>  <chr>  <chr>  <chr>  <chr>  
    ## 1 ASIAN AND PACIFIC ISLANDER ethan  jayden jayden jayden ryan   ethan  
    ## 2 BLACK NON HISPANIC         noah   noah   ethan  ethan  jayden jayden 
    ## 3 HISPANIC                   liam   liam   liam   jayden jayden jayden 
    ## 4 WHITE NON HISPANIC         joseph david  joseph david  joseph michael

``` r
sp_dt = 
  filter(
    babynames_dt, 
    gender == "MALE", 
    ethnicity == "WHITE NON HISPANIC", 
    year_of_birth == 2016 ) %>% 
  ggplot(aes(x = rank, y = count)) + geom_point()

sp_dt
```

![](p8105_hw2_kq2127_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->
